### ISSUE TITLE
v1.0 메인페이지 및 북마크 페이지

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#1]
### Todo

- [x] 모집중 태그 UI
- [x] 모집중 태그 기능
- [x] 지역 태그 UI
- [x] 지역 태그 기능
- [x] 종목 태그 UI
- [x] 종목 태그 기능
- [x] 리스트 컴포넌트 및 북마크 UI
- [x] 검색 UI
- [x] 검색 기능
- [x] 페이지네비게이션 UI
- [x] 페이지네비게이션 기능
- [x] 북마크 기능

### 작업 기간

2024.04.20 ~ 2024.05.14

**Comment by Banal972** [comment]
종목, 지역 태그 같은경우
빈값을 보내면 API 오류가 발생하는 현상이 있습니다.
창호님에게 전달하여 API 수정을 요청하였습니다.
