### ISSUE TITLE
v1.0 ailas 경로 정리 및 기능 추가

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#28]
### Todo

- [x] ailas 코드 정리
- [x] 오픈 팝업 추가
- [x] 리스트 : 최신순 , 인기순, 오래된순 필터링

### 작업 기간

2024.05.14 ~
