### ISSUE TITLE
v1.0 마이페이지 기능 개선

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#30]
### Todo

- [x] 마이페이지 중복확인
- [x] 마이페이지 비밀번호 변경
- [x] 마이페이지 닉네임 변경 

### 작업 기간

2024.05.14 ~ 2024.05.14

**Comment by Banal972** [comment]
추가사항

- [x] 변경시에 화면에 바로 보일수 있도록 수정해야 할것 같습니다.
