### ISSUE TITLE
v1.0 UI 정리 및 각종 버그

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#35]
### Todo

**상세내용**
- [x] 상세내용 수정
- [x] 상세내용 북마크 버그

**홈**
- [x] 정렬버튼 버그
- [x] 팝업 그림자 UI 수정
- [x] 큰 화면 배너 짤림 UI 수정
- [x] 북마크 버그

**작성페이지**
- [x] 텍스트 에디터 추가

**카드 컴포넌트**
- [x] 모집중 모집완료 색상 수정

### 작업 기간

2024.05.16 ~ 2024.05.16
