### ISSUE TITLE
Auth 페이지 추가 및 수정

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#42]
### Todo

- [x] 회원가입 페이지 UI
- [x] 마이페이지 UI 수정
- [x] 이메일 인증 추가
- [x] 회원탈퇴 추가

### 작업 기간

2024.05.26
