### ISSUE TITLE
메인, 작성 UI 수정 및 기능 추가

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#44]
### Todo

- [x] 메인페이지 UI 변경
- [x] 추천게시물 UI 추가
- [x] 추천게시물 기능 추가
- [x] 작성페이지 UI 변경
- [x] 댓글기능 추가

### 작업 기간

2024.05.27 ~
