### ISSUE TITLE
렌더링 페이지 및 모달창

### ISSUE THREAD

**Issue by Banal972** [gugumo-service/gugumo_frontend#50]
### Todo

- [x] 렌딩 페이지 생성
- [x] 렌딩 페이지 애니메이션 구현
- [x] 커스텀 모달창 구현

### 작업 기간

2024.06.05 ~
